spring:
  cloud:
    function:
      definition: aggregateWeather;alarmProcessor
    stream:
      bindings:
        aggregateWeather-in-0:
          destination: weather-data
        aggregateWeather-out-0:
          destination: agg-weather-data
        alarmProcessor-in-0:
          destination: agg-weather-data
        alarmProcessor-out-0:
          destination: weather-alarms
      kafka:
        streams:
          binder:
            replicationFactor: 1
            configuration:
              default:
                timestamp:
                  extractor: streams.service.WeatherDataTimestampExtractor
            functions:
              aggregateWeather:
                application-id: aggregateWeather-0.0.2
              alarmProcessor:
                application-id: alarmProcessor-0.0.1

logging:
  level:
    org:
      apache:
        kafka:
          streams: debug